name: vpge-gryphon
recipe: drupal9
config:
  webroot: docroot
  php: '7.4'
  xdebug: false
proxy:
  appserver:
    - vpge.lndo.site
    - diversityworks.lndo.site
services:
  appserver:
    build_as_root:
      - pecl install pcov
      - docker-php-ext-enable pcov
    build:
      - composer install
      - composer init-lando
    ssl: true
    config:
      php: lando/php.ini
    # Uncomment the below for behat testing
    # overrides:
    #   environment:
    #       BEHAT_PARAMS: >-
    #         {
    #           "extensions" : {
    #             "Behat\\MinkExtension" : {
    #               "base_url" : "https://appserver/"
    #             }
    #           }
    #         }
  database:
    type: mysql:5.7
    portforward: 33061
    creds:
      user: drupal
      password: drupal
      database: vpge
  diversityworks:
    type: mysql:5.7
    portforward: 33062
    creds:
      user: drupal
      password: drupal
      database: diversityworks
  # Uncomment the below for behat testing.
  # chromedriver:
  #   type: compose
  #   services:
  #     image: robcherry/docker-chromedriver:latest
  #     expose:
  #       - "4444"
  #     environment:
  #       CHROMEDRIVER_WHITELISTED_IPS: ""
  #       CHROMEDRIVER_URL_BASE: "/wd/hub"
  #     security_opt:
  #       - seccomp:unconfined
  #     command: ["/usr/local/bin/supervisord", "-c", "/etc/supervisord.conf"]
  # testresults:
  #   type: nginx
  #   webroot: artifacts
tooling:
  blt:
    service: appserver
    cmd: /app/vendor/bin/blt
  git:
    service: appserver
  phpcs:
    service: appserver
    cmd: "/app/vendor/bin/phpcs --standard=Drupal,DrupalPractice"
    options:
    description: Run phpcs for given folder or file.
  phpunit:
    service: appserver
    cmd: "/app/vendor/bin/phpunit -c /app/docroot/core"
    description: Run phpunit tests
