name: vpge-gryphon
recipe: drupal10
config:
  webroot: docroot
  php: '8.2'
  xdebug: false
proxy:
  appserver:
    - vpge.lndo.site
    - diversityworks.lndo.site
  adminer:
    - adminervpge.lndo.site
services:
  appserver:
    build_as_root:
      - pecl install pcov
      - docker-php-ext-enable pcov
    build:
      - composer install
      - composer init-lando
    volumes:
      - ~/.acquia:/var/www/.acquia
      - ~/.ssh:/var/www/.ssh
    ssl: true
    config:
      php: lando/php.ini
    # Uncomment the below for behat testing
      overrides:
        environment:
          MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless"]}}, "http://chromedriver:4444"]'
          BEHAT_PARAMS: >-
            {
              "extensions" : {
                "Behat\\MinkExtension" : {
                  "base_url" : "http://vpge.lndo.site/"
                }
              }
            }
  database:
    type: mysql:5.7
    portforward: 33061
    creds:
      user: drupal
      password: drupal
      database: vpge
  adminer:
    type: compose
    services:
      image: dehy/adminer
      command: /bin/s6-svscan /etc/services.d
    portforward: true
  diversityworks:
    type: mysql:5.7
    portforward: 33062
    creds:
      user: drupal
      password: drupal
      database: diversityworks
  # Uncomment the below for behat testing
      overrides:
        environment:
          MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless"]}}, "http://chromedriver:4444"]'
          BEHAT_PARAMS: >-
            {
              "extensions" : {
                "Behat\\MinkExtension" : {
                  "base_url" : "http://diversityworks.lndo.site/"
                }
              }
            }
  # Uncomment the below for behat testing.
  chromedriver:
    type: lando
    api: 3
    ssl: false
    sslExpose: false
    services:
      user: root
      image: selenium/standalone-chrome:115.0
      command: /opt/bin/entry_point.sh
      volumes:
        - /dev/shm:/dev/shm
      ports:
        - 4444
tooling:
  blt:
    service: appserver
    cmd: /app/vendor/bin/blt
  git:
    service: appserver
  phpcs:
    service: appserver
    cmd: "/app/vendor/bin/phpcs --standard=Drupal,DrupalPractice"
    options:
    description: Run phpcs for given folder or file.
  phpunit:
    service: appserver
    cmd: "/app/vendor/bin/phpunit -c /app/docroot/core"
    description: Run phpunit tests
